baseURL = 'https://naoshi-isaki.github.io/research/'
languageCode = 'ja-jp'
title = 'Naoshi Isaki Research'
theme = 'qubt'

[pagination]
    pagerSize = 10

[params]
    # ポートフォリオ風のトップページ設定
    description = "Political Science Researcher"
    author = "Naoshi Isaki"
    
    # 以前の「1件目の強調」などはこのテーマ独自のスタイルに置き換わります
    # このテーマは標準で非常に綺麗なカードレイアウトを持っています
