baseURL = 'https://naoshi-isaki.github.io/research/'
languageCode = 'ja-jp'
title = 'Naoshi Isaki Research'
theme = 'qubt'

[pagination]
    pagerSize = 10

[params.author]
    name = "Naoshi Isaki"
    description = "Political Science Researcher"
    # 必要であれば画像などもここに追加できます
    avatar = "images/profile.jpg"
    # ここにSNSリンクを羅列（テーマの仕様に合わせる）
    github = "https://github.com/naoshi-isaki"
    twitter = "https://twitter.com/あなたのユーザー名"
    facebook = "https://facebook.com/あなたのユーザー名"
    linkedin = "https://linkedin.com/in/あなたのユーザー名"

[params]
  [params.author]
    name = "Naoshi Isaki"
    # ここに書いた内容が、画像の下（h2タグ）に表示されます
    description = "政治学研究者 | 政治的対立軸とデータ分析の研究アーカイブ"
    avatar = "images/profile.jpg"
    # SNSリンクの設定

[[params.social]]
    name = "github"
    icon = "github"
    url = "https://github.com/naoshi-isaki"

[[params.social]]
    name = "twitter"
    icon = "twitter"
    url = "https://twitter.com/あなたのユーザー名"

[[params.social]]
    name = "researchmap"
    icon = "link" # Researchmap専用アイコンはないため、汎用リンクアイコンを使用
    url = "https://researchmap.jp/naoshi-isaki"

[[params.social]]
    name = "email"
    icon = "mail"
    url = "mailto:あなたのメールアドレス"

# 業績：論文や学会発表のページ
[[menu.main]]
    identifier = "research"
    name = "research"
    url = "/research/"
    weight = 10

# 教育：講義資料やシラバス
[[menu.main]]
    identifier = "education"
    name = "education"
    url = "/education/"
    weight = 20

# ブログ：日々の研究メモ（既存の post フォルダ）
[[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog/"
    weight = 30

# Researchmap：外部サイトへのリンク
[[menu.main]]
    identifier = "researchmap"
    name = "Researchmap"
    url = "https://researchmap.jp/nisaki"
    weight = 40
