baseURL = 'https://naoshi-isaki.github.io/research/'
languageCode = 'ja-jp'
title = 'N.Isaki Research'
theme = 'qubt'

[pagination]
    pagerSize = 10

[params]
    # L1nkrã‚’æœ‰åŠ¹åŒ–ï¼ˆéšå±¤ã«æ³¨æ„ï¼‰
    [params.author]
    name = "Naoshi Isaki"
    # ãƒ‡ãƒ¢ã‚µã‚¤ãƒˆã® h2 ã‚¿ã‚°ã«ç›¸å½“ã™ã‚‹éƒ¨åˆ†
    greeting = "Graduate School of Policy and Management, Doshisha University"
    image = "/images/profile.jpg"
    icon = "ğŸ‘‹"

    # SNSãƒªãƒ³ã‚¯è¨­å®šï¼ˆã‚­ãƒ¼åã‚’æŒ‡å®šã™ã‚‹ã“ã¨ã§ã‚¢ã‚¤ã‚³ãƒ³ãŒè‡ªå‹•ç”Ÿæˆã•ã‚Œã¾ã™ï¼‰
    [[params.links]]
        website = "https://researchmap.jp/nisaki"
    [[params.links]]
        bluesky = "https://bsky.app/profile/nisaki04.bsky.social"
    [[params.links]]
        x-twitter = "https://twitter.com/nisaki04"
    [[params.links]]
        email = "mailto:cxzk1001@mail3.doshisha.ac.jp"

    # è¡¨ç¤ºè¨­å®š
    columns = 4
    icontext = true

# --- ãƒ¡ãƒ‹ãƒ¥ãƒ¼è¨­å®š ---
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5

[[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 10

[[menu.main]]
    identifier = "education"
    name = "Education"
    url = "/education/"
    weight = 20

[[menu.main]]
    identifier = "courses"
    name = "Courses"
    url = "/courses/"
    weight = 30

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "https://naoshi-isaki.github.io/nisaki-research/"
    weight = 40
