baseURL = 'https://naoshi-isaki.github.io/research/'
languageCode = 'ja-jp'
title = 'Naoshi Isaki Research'
theme = 'qubt'

[pagination]
    pagerSize = 10

[params.author]
    name = "Naoshi Isaki"
    description = "Political Science Researcher"
    # 必要であれば画像などもここに追加できます
    avatar = "images/profile.jpg"
