baseURL = 'https://naoshi-isaki.github.io/research/'
languageCode = 'ja-jp'
title = 'Naoshi Isaki Research'
theme = 'qubt'

[pagination]
    pagerSize = 10

# すべての独自パラメータは [params] の下に配置します
[params]
    # メニューを小さくするCSS（static/css/custom.css を作成済みの場合）
    customCSS = ["css/custom.css"]

    # 著者情報はここ1箇所にまとめます
    [params.author]
        name = "Naoshi Isaki"
        description = "政治学研究者 | 政治的対立軸とデータ分析の研究アーカイブ"
        avatar = "images/profile.jpg"

# SNSリンクの設定（二重括弧 [[ ]] を使用）
[[params.social]]
    name = "github"
    icon = "github"
    url = "https://github.com/naoshi-isaki"

[[params.social]]
    name = "twitter"
    icon = "twitter"
    url = "https://twitter.com/あなたのユーザー名"

[[params.social]]
    name = "researchmap"
    icon = "link"
    url = "https://researchmap.jp/naoshi-isaki"

[[params.social]]
    name = "email"
    icon = "mail"
    url = "mailto:あなたのメールアドレス"

# メニュー設定
[[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 10

[[menu.main]]
    identifier = "education"
    name = "Education"
    url = "/education/"
    weight = 20

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/post/" # あなたのフォルダ構成が content/post/ ならここを /post/ にします
    weight = 30

[[menu.main]]
    identifier = "researchmap"
    name = "Researchmap"
    url = "https://researchmap.jp/nisaki"
    weight = 40
