baseURL = 'https://naoshi-isaki.github.io/research/'
languageCode = 'ja-jp'
title = 'Naoshi Isaki Research'
theme = 'qubt'

[pagination]
    pagerSize = 10

# [params] という親要素を書かずに、直接指定してみます
[author]
    name = "Naoshi Isaki"
    description = "政治学研究者 | 政治的対立軸とデータ分析の研究アーカイブ"
    avatar = "images/profile.jpg"

[params]
    customCSS = ["css/custom.css"]
    # 予備としてこちらにも書いておきます
    [params.author]
        name = "Naoshi Isaki"
        description = "政治学研究者 | 政治的対立軸とデータ分析の研究アーカイブ"

# SNS設定
[[params.social]]
    name = "github"
    icon = "github"
    url = "https://github.com/naoshi-isaki"

# メニュー設定
[[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 10

[[menu.main]]
    identifier = "education"
    name = "Education"
    url = "/education/"
    weight = 20

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/post/"
    weight = 30
